

/**
 * Từ điển. Key = chuỗi gốc y hệt trong editor (khoảng trắng đầu/cuối được bỏ qua).
 *
 * Mẹo: dùng {0}, {1}... cho phần số động.
 *   "Level 7" trên UI sẽ tự khớp với key "Level {0}" và ghép lại thành "レベル7".
 */
export const LOCALIZE_DATA = {
    'Start': {
        en: 'Start',
        es: 'Empezar',
        pt: 'Começar',
        fr: 'Commencer',
        de: 'Start',
        it: 'Inizia',
        ru: 'Начать',
        tr: 'Başla',
        ja: 'スタート',
        ko: '시작',
        'zh-cn': '开始',
        'zh-tw': '開始',
        th: 'เริ่ม',
        id: 'Mulai',
        ar: 'ابدأ',
        hi: 'शुरू करें',
    },
    'Play Now': {
        en: 'Play Now',
        es: 'Jugar ahora',
        pt: 'Jogar agora',
        fr: 'Jouer maintenant',
        de: 'Jetzt spielen',
        it: 'Gioca ora',
        ru: 'Играть сейчас',
        tr: 'Şimdi oyna',
        ja: '今すぐプレイ',
        ko: '지금 플레이',
        'zh-cn': '立即游戏',
        'zh-tw': '立即遊玩',
        th: 'เล่นเลย',
        id: 'Main sekarang',
        ar: 'العب الآن',
        hi: 'अभी खेलें',
    },
    'Install Now': {
        en: 'Install Now',
        es: 'Instalar ahora',
        pt: 'Instalar agora',
        fr: 'Installer maintenant',
        de: 'Jetzt installieren',
        it: 'Installa ora',
        ru: 'Установить',
        tr: 'Şimdi yükle',
        ja: '今すぐインストール',
        ko: '지금 설치',
        'zh-cn': '立即安装',
        'zh-tw': '立即安裝',
        th: 'ติดตั้งเลย',
        id: 'Instal sekarang',
        ar: 'ثبّت الآن',
        hi: 'अभी इंस्टॉल करें',
    },
    'Tap to Play': {
        en: 'Tap to Play',
        es: 'Toca para jugar',
        pt: 'Toque para jogar',
        fr: 'Appuyez pour jouer',
        de: 'Zum Spielen tippen',
        it: 'Tocca per giocare',
        ru: 'Нажмите, чтобы играть',
        tr: 'Oynamak için dokun',
        ja: 'タップしてプレイ',
        ko: '탭하여 플레이',
        'zh-cn': '点击开始游戏',
        'zh-tw': '點擊開始遊戲',
        th: 'แตะเพื่อเล่น',
        id: 'Ketuk untuk main',
        ar: 'انقر للعب',
        hi: 'खेलने के लिए टैप करें',
    },
    'Try Again': {
        en: 'Try Again',
        es: 'Reintentar',
        pt: 'Tentar de novo',
        fr: 'Réessayer',
        de: 'Nochmal versuchen',
        it: 'Riprova',
        ru: 'Попробовать снова',
        tr: 'Tekrar dene',
        ja: 'もう一度',
        ko: '다시 시도',
        'zh-cn': '再试一次',
        'zh-tw': '再試一次',
        th: 'ลองอีกครั้ง',
        id: 'Coba lagi',
        ar: 'حاول مرة أخرى',
        hi: 'फिर से कोशिश करें',
    },
    'Continue': {
        en: 'Continue',
        es: 'Continuar',
        pt: 'Continuar',
        fr: 'Continuer',
        de: 'Weiter',
        it: 'Continua',
        ru: 'Продолжить',
        tr: 'Devam et',
        ja: 'つづける',
        ko: '계속하기',
        'zh-cn': '继续',
        'zh-tw': '繼續',
        th: 'ดำเนินการต่อ',
        id: 'Lanjutkan',
        ar: 'متابعة',
        hi: 'जारी रखें',
    },
    'Congratulations!': {
        en: 'Congratulations!',
        es: '¡Felicidades!',
        pt: 'Parabéns!',
        fr: 'Félicitations !',
        de: 'Glückwunsch!',
        it: 'Congratulazioni!',
        ru: 'Поздравляем!',
        tr: 'Tebrikler!',
        ja: 'おめでとう！',
        ko: '축하합니다!',
        'zh-cn': '恭喜！',
        'zh-tw': '恭喜！',
        th: 'ยินดีด้วย!',
        id: 'Selamat!',
        ar: 'تهانينا!',
        hi: 'बधाई हो!',
    },
    'You Win!': {
        en: 'You Win!',
        es: '¡Ganaste!',
        pt: 'Você venceu!',
        fr: 'Gagné !',
        de: 'Gewonnen!',
        it: 'Hai vinto!',
        ru: 'Вы победили!',
        tr: 'Kazandın!',
        ja: '勝利！',
        ko: '승리!',
        'zh-cn': '你赢了！',
        'zh-tw': '你贏了！',
        th: 'คุณชนะ!',
        id: 'Kamu menang!',
        ar: 'لقد فزت!',
        hi: 'आप जीत गए!',
    },
    'You Lose!': {
        en: 'You Lose!',
        es: '¡Perdiste!',
        pt: 'Você perdeu!',
        fr: 'Perdu !',
        de: 'Verloren!',
        it: 'Hai perso!',
        ru: 'Вы проиграли!',
        tr: 'Kaybettin!',
        ja: '敗北！',
        ko: '패배!',
        'zh-cn': '你输了！',
        'zh-tw': '你輸了！',
        th: 'คุณแพ้!',
        id: 'Kamu kalah!',
        ar: 'لقد خسرت!',
        hi: 'आप हार गए!',
    },

    // --- Ví dụ chuỗi có phần số động: dùng {0} ---
    'Level {0}': {
        en: 'Level {0}',
        es: 'Nivel {0}',
        pt: 'Nível {0}',
        fr: 'Niveau {0}',
        de: 'Level {0}',
        it: 'Livello {0}',
        ru: 'Уровень {0}',
        tr: 'Seviye {0}',
        ja: 'レベル{0}',
        ko: '레벨 {0}',
        'zh-cn': '第{0}关',
        'zh-tw': '第{0}關',
        th: 'ด่าน {0}',
        id: 'Level {0}',
        ar: 'المستوى {0}',
        hi: 'लेवल {0}',
    },
    'Score: {0}': {
        en: 'Score: {0}',
        es: 'Puntos: {0}',
        pt: 'Pontos: {0}',
        fr: 'Score : {0}',
        de: 'Punkte: {0}',
        it: 'Punti: {0}',
        ru: 'Очки: {0}',
        tr: 'Puan: {0}',
        ja: 'スコア: {0}',
        ko: '점수: {0}',
        'zh-cn': '分数: {0}',
        'zh-tw': '分數: {0}',
        th: 'คะแนน: {0}',
        id: 'Skor: {0}',
        ar: 'النقاط: {0}',
        hi: 'स्कोर: {0}',
    },
    '{0}s left': {
        en: '{0}s left',
        es: 'Quedan {0}s',
        pt: 'Restam {0}s',
        fr: '{0}s restantes',
        de: 'Noch {0}s',
        it: '{0}s rimasti',
        ru: 'Осталось {0} с',
        tr: '{0}sn kaldı',
        ja: '残り{0}秒',
        ko: '{0}초 남음',
        'zh-cn': '剩余{0}秒',
        'zh-tw': '剩餘{0}秒',
        th: 'เหลือ {0} วินาที',
        id: 'Sisa {0} detik',
        ar: 'بقي {0} ثانية',
        hi: '{0} सेकंड बाकी',
    },

    'Best brain-training puzzle game': {
        en: 'Best brain-training puzzle game',
        es: 'El mejor puzzle para entrenar el cerebro',
        pt: 'O melhor puzzle para treinar o cérebro',
        fr: 'Le meilleur puzzle pour entraîner le cerveau',
        de: 'Das beste Puzzle-Spiel zum Gehirntraining',
        it: 'Il miglior puzzle per allenare il cervello',
        ru: 'Лучшая головоломка для тренировки мозга',
        tr: 'Beyin geliştiren en iyi bulmaca oyunu',
        ja: '脳トレに最適なパズルゲーム',
        ko: '두뇌 훈련을 위한 최고의 퍼즐 게임',
        'zh-cn': '最佳脑力训练益智游戏',
        'zh-tw': '最佳腦力訓練益智遊戲',
        th: 'เกมปริศนาฝึกสมองที่ดีที่สุด',
        id: 'Game puzzle terbaik untuk melatih otak',
        ar: 'أفضل لعبة ألغاز لتدريب العقل',
        hi: 'दिमागी कसरत के लिए बेहतरीन पज़ल गेम',
        vi: "Trò chơi giải đố rèn luyện trí não tốt nhất"
    },

'Only IQ >160 can escape Pink car': {
    en: 'Only IQ >160 can escape Pink car',
    es: 'Solo IQ >160 puede escapar del coche rosa',
    pt: 'Só IQ >160 consegue escapar do carro rosa',
    fr: 'Seul un QI >160 peut échapper à la voiture rose',
    de: 'Nur IQ >160 kann dem pinken Auto entkommen',
    it: 'Solo chi ha un QI >160 può sfuggire all’auto rosa',
    ru: 'Только IQ >160 поможет сбежать от розовой машины',
    tr: 'Sadece IQ >160 olanlar pembe arabadan kaçabilir',
    ja: 'IQ160超えだけがピンクの車から脱出できる',
    ko: 'IQ 160 이상만 핑크 자동차에서 탈출 가능',
    'zh-cn': '只有IQ>160才能逃出粉色汽车',
    'zh-tw': '只有IQ>160才能逃出粉紅色汽車',
    th: 'เฉพาะ IQ >160 เท่านั้นที่หนีจากรถสีชมพูได้',
    id: 'Hanya IQ >160 yang bisa kabur dari mobil pink',
    ar: 'فقط من يملك IQ >160 يمكنه الهروب من السيارة الوردية',
    hi: 'सिर्फ IQ >160 वाले ही गुलाबी कार से बच सकते हैं',
    vi: 'Chỉ IQ >160 mới thoát được xe hồng',
},
};
